### ISSUE TITLE
_tkinter.TclError on Mac OS

### ISSUE THREAD

**Issue by deepaerial** [ppruchnicki/pdf_merger#2]
On Mac OS Big Sur error occurs when trying running `pipenv run python -m PDF_merger`:

```
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/deepaerial/Projects/pdf_merger/PDF_merger.py", line 118, in <module>
    root.tk.call("source", os.path.join(dir_path, "theme/sun-valley.tcl"))
_tkinter.TclError: version conflict for package "Tk": have 8.5.9, need 8.6
```

**Comment by deepaerial** [comment]
Found possible [solution](https://stackoverflow.com/questions/60469202/unable-to-install-tkinter-with-pyenv-pythons-on-macos/60469203#60469203) but have not tested it yet.
